---
title: "Données"
output: github_document
---

# Données nationales

```{r message=FALSE, warning=FALSE}
library(data.table)

liste_prenoms <- fread("donnees/nat2018.csv")
```

```{r}
str(liste_prenoms)
```


On supprime les années XXXX et les prénoms _PRENOMS_RARES, voir <https://www.insee.fr/fr/statistiques/2540004#documentation>.
```{r}
liste_prenoms <- liste_prenoms[preusuel != "_PRENOMS_RARES" & annais != "XXXX", ]
```


```{r}
liste_prenoms <- liste_prenoms[, .(sexe = as.factor(ifelse(sexe == 1, "Masculin", "Feminin")),
                                  prenom = preusuel,
                                  annee = as.numeric(annais),
                                  nombre)]
```

```{r}
# vérification des valeurs manquantes
apply(is.na(liste_prenoms), 2, sum)
```


```{r}
summary(liste_prenoms, na.rm = TRUE)
```


# Données par département

```{r}
liste_prenoms_dep <- fread("donnees/dpt2018.csv")
```

```{r}
str(liste_prenoms_dep)
```

On supprime les années XXXX, les prénoms _PRENOMS_RARES et les départements XX.

```{r}
liste_prenoms_dep <- liste_prenoms_dep[preusuel != "_PRENOMS_RARES" & annais != "XXXX" & dpt != "XX", ]
```


```{r}
liste_prenoms_dep <- liste_prenoms_dep[, .(sexe = as.factor(ifelse(sexe == 1, "Masculin", "Feminin")),
                                          prenom = preusuel,
                                          annee = as.numeric(annais),
                                          dpt,
                                          nombre)]
```

```{r}
# vérification des valeurs manquantes
apply(is.na(liste_prenoms_dep), 2, sum)
```

```{r}
summary(liste_prenoms_dep, na.rm = TRUE)
```